import type { Metadata } from 'next'
import '@/theme/globals.css'
import RootLayout from '@sec/gui-seconder/layouts/root-layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default RootLayout
